# Permalinks
permalink:        /post/:title.html

# Setup
url:              https://debugjoker.github.io
# img_url:          https://infp.github.io/images

# Set to '' in case of hosting on `https://<your-github-name>.github.io`
baseurl:          ''

title:            '夏木逢秋'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  关于[代码](https://debugjoker.github.io/code/)、[生活](https://debugjoker.github.io/life/)、[宇宙](https://debugjoker.github.io/read/)和[一切](/)。


# Google Analytics tracking ID
# TODO: 如果使用本主题，请务必替换此处的 Google 统计代码，否则你的站点将无法获得统计数据
analytics:        'UA-137924682-1'

# Fallback image and color if not overwritten for tag or post
image:            /public/images/flower.jpg
color:            '#dc322f'

author:
  name:           '夏木逢秋'
  email:          debugjoker@hotmail.com
  github:         debugjoker
  photo:          /public/images/me.jpg


  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    我是夏木逢秋，热爱生活，喜欢与人交流分享。如果你觉得本文不错，可略表心意，[请我喝一杯咖啡](https://debugjoker.github.io/about.html#buymeacoffee)。


compress_html:
  clippings:      all
  comments:       ["<!--", "-->"]
  endings:        all
  startings:      [html, head, body]

sass:
  sass_dir:       /public/css
  style:          compressed
